import {
  schemeAccent,
  schemeBlues,
  schemeBrBG,
  schemeBuGn,
  schemeBuPu,
  schemeDark2,
  schemeGnBu,
  schemeGreens,
  schemeGreys,
  schemeOranges,
  schemeOrRd,
  schemePaired,
  schemePastel1,
  schemePastel2,
  schemePiYG,
  schemePRGn,
  schemePuBu,
  schemePuBuGn,
  schemePuOr,
  schemePuRd,
  schemePurples,
  schemeRdBu,
  schemeRdGy,
  schemeRdPu,
  schemeRdYlBu,
  schemeRdYlGn,
  schemeReds,
  schemeSet1,
  schemeSet2,
  schemeSet3,
  schemeSpectral,
  schemeYlGn,
  schemeYlGnBu,
  schemeYlOrBr,
  schemeYlOrRd,
} from 'd3-scale-chromatic'

export default {
  schemeAccent,
  schemeBlues: schemeBlues[9],
  schemeBrBG: schemeBrBG[11],
  schemeBuGn: schemeBuGn[9],
  schemeBuPu: schemeBuPu[9],
  schemeDark2,
  schemeGnBu: schemeGnBu[9],
  schemeGreens: schemeGreens[9],
  schemeGreys: schemeGreys[9],
  schemeOranges: schemeOranges[9],
  schemeOrRd: schemeOrRd[9],
  schemePaired,
  schemePastel1,
  schemePastel2,
  schemePiYG: schemePiYG[11],
  schemePRGn: schemePRGn[11],
  schemePuBu: schemePuBu[9],
  schemePuBuGn: schemePuBuGn[9],
  schemePuOr: schemePuOr[11],
  schemePuRd: schemePuRd[9],
  schemePurples: schemePurples[9],
  schemeRdBu: schemeRdBu[11],
  schemeRdGy: schemeRdGy[11],
  schemeRdPu: schemeRdPu[9],
  schemeRdYlBu: schemeRdYlBu[11],
  schemeRdYlGn: schemeRdYlGn[11],
  schemeReds: schemeReds[9],
  schemeSet1,
  schemeSet2,
  schemeSet3,
  schemeSpectral: schemeSpectral[11],
  schemeYlGn: schemeYlGn[9],
  schemeYlGnBu: schemeYlGnBu[9],
  schemeYlOrBr: schemeYlOrBr[9],
  schemeYlOrRd: schemeYlOrRd[9],
}
